include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = MiniTaPrefs
MiniTaPrefs_FILES = MTRootListController.m
MiniTaPrefs_FRAMEWORKS = UIKit Foundation CoreFoundation
MiniTaPrefs_PRIVATE_FRAMEWORKS = Preferences
MiniTaPrefs_CFLAGS = -fobjc-arc
MiniTaPrefs_INSTALL_PATH = /Library/PreferenceBundles
include $(THEOS_MAKE_PATH)/bundle.mk
